name = "aoc_julia"
uuid = "f6714f57-8430-4c90-8927-e3b85f846b76"
authors = ["jgsimard <jeangab23@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BenchmarkTools = "1.5.0"
StatsBase = "0.34.3"
